<!DOCTYPE html>
<html style="background-color: black;">

<head>
    <title>ព័ត៌មានប្រចាំថ្ងៃ</title>
    <link rel="icon" href="istockphoto-528874375-612x612.jpg" type="image/x-icon">
</head>

<body>
    <header style="background-color: yellow;">
        <marquee>
            <h2>
                <font color="red">ព័ត៌មានទាន់ហេតុការណ៏ប្រចាំថ្ងៃ</font>
            </h2>
        </marquee>
    </header>
    <h1 align="center">
        <font style="color: white;">ផលប៉ះពាល់នៃបារី</font>
    </h1>
    <hr size="5" color="yellow">
    <img src="photo_2023-09-20_15-01-50.jpg" alt="photo_2023-09-20_15-01-50.jpg" width="400px" height="400px"
        hspace="5px" vspace="5px" align="left">
    <p>
        <font color="white"> ការ​ជក់​បារី ផ្តល់​ផល​វិបាក​ពីរ​យ៉ាង​ដល់​សុខ​ភាព​គឺ​ ៖ -ទីមួយ
            អ្នកជក់​បារី​នឹង​ក្លាយ​ជា​ញៀន​បារី​យ៉ាង​ឆាប់​រហ័ស​ដោយ​សារ​នី​កូទីន ។ -ទីពីរ
            ការជក់​បារី​អាច​បណ្តាល​ឱ្យ​ស្លាប់<br>
            និង​មាន​ជំងឺ​ធ្ងន់​ធ្ងរ​ជា​ច្រើន ដែល​បណ្តាល​ឱ្យ​មាន​ការ​​ប្រឈម​នឹង​ការស្លាប់​មុនអាយុ ។ ការញៀន​នី​កូទីន
            ផ្សែង​បារី​មាន​នី​កូទីន ដែល​ជា​សារធាតុ​ញៀន​មួយ​ដែល​ធ្វើ​ឱ្យ<br>
            ​អ្នក​ជក់​បារី​កាន់តែ​ចង់​ជក់​បារី​​ថែមទៀត ។ មិន​តែ​ប៉ុណ្ណោះ
            នី​កូ​ទីន​ធ្វើ​ឱ្យ​មាន​រោគ​សញ្ញា​ញៀន​ដែលពិបាក​ទ្រាំ​ ។
            ការ​មាន​​អារម្មណ៍​ល្អ​នៅ​ពេល​មាន​នី​កូ​ទីន​នៅ​ក្នុង​ខ្លួន<br>
            និង​​ការ​មានអារម្មណ៍​​មិន​ល្អ​នៅ​ពេល​គ្មាន​វា​នោះ
            ធ្វើ​ឱ្យ​មាន​​ការ​ពិបាកយ៉ាង​ខ្លាំង​ក្នុង​ការ​ជំនះ​ការ​ញៀន​បារី​នេះ ។ ការញៀន​នី​កូទីន
            គឺជា​ការ​ញៀន​មួយ​ដែល​ពិបាក​ផ្តាច់<br>
            ក្នុង​ចំណោម​ការ​ញៀន​សារធាតុ​ផ្សេងៗ​ទៀត ដែល​ពិបាក​ផ្តាច់ ។​
            ការ​​ប្រើ​ប្រាស់​ថ្នាំ​ជក់​គ្រប់​ទំរង់​ទាំង​អស់​សុទ្ធ​តែ​បណ្តាល​ឱ្យ​មាននី​កូ​ទីន​ក្នុង​បរិមាណ​ខុសៗ​គ្នា​
            ជ្រាប​ចូល​ទៅ<br>
            ​ក្នុង​ចរន្ត​ឈាម​របស់​អ្នក​ប្រើ​ប្រាស់ ។ ជា​មធ្យម​នី​កូ​ទីន​ចូល​ដល់​ខួរ​ក្បាល​ក្នុង​រយៈ​ពេល​១០​វិនាទី
            បន្ទាប់​ពី​ផ្សែង​បារីត្រូវ​បាន​ហឺត​ចូល ។ បន្ទាប់​ពី​មាន​ការ​ប្រើ​ប្រាស់​ថ្នាំ​ជក់​<br>
            មួយ​រយៈ​មក ការ​ញៀន​នឹង​កើត​​ឡើង ។ បរិ​មាណ​ ចំនួន​ដង និង​ល្បឿន​នៃ​ការ​ជ្រាបរបស់​នី​កូ​ទីន
            ហាក់​ដូច​ជា​មាន​ទំនាក់​ទំនង​ដោយ​ផ្ទាល់​ជា​មួយ​ឥទ្ធិ​ពល​នៃ​ការ​ញៀន​<br>
            ដែល​បាន​កើត​ឡើង ។ ការ​ញៀន​នី​កូទីន មាន​ឥទ្ធិ​ពល​យ៉ា​ង​ខ្លាំង ។
            នៅ​ពេល​ដែល​នរ​ណា​ម្នាក់​បាន​ក្លាយ​ជា​អ្នក​ញៀន​បារីហើយ នោះ​គេ​នឹង​ត្រូវ​តែ​បន្ត​ជក់​បារី ដើម្បី​ទទួល<br>
            ​នូវ​អ្វី​ដែល​ការ​ជក់​នោះ​បាន​ផ្តល់ សំរាប់​បំពេញ​តំរូវ​ការ​ផ្លូវកាយ និង​ផ្លូវ​អារម្មណ៍​របស់​ពួក​គេ ។<br>
            ប៉ុន្តែ​ជា​អកុសល អារម្មណ៍​ល្អ​ដែល​អ្នក​ជក់​បារី​បាន​ទទួល​ពី​ការ​ជក់នោះ មាន​រយៈ​ពេល​យ៉ាង​ខ្លី
            ជា​ហេតុ​ធ្វើ​ឱ្យ​ពួក​គេ​ចាប់​ផ្តើម​ចង់​ជក់​បារី មួយ​ដើម​ទៀត ក្នុង​រយៈ​ពេល​<br>
            ដ៏​ខ្លី ។ បញ្ហា​មួយ​ទៀត​ដែល​កើត​ឡើង​ចំពោះ​អ្នកជក់​បារី គឺ​កាល​ណា​ពួក​គេ​ជក់​បារីកាន់តែ​ច្រើន​
            នោះ​ជាតិ​នី​កូ​ទីន នឹង​ចូល​ទៅ​ក្នុង​ខ្លួន​គេ​កាន់តែ​ច្រើន ដែល​បណ្តាល​ឱ្យ​<br>
            មាន​ការ​ញៀន​កាន់​តែ​ខ្លាំង ។ ជា​លទ្ធ​ផល​ ពួក​គេ​ត្រូវ​តែ​ជក់​បារី​កាន់តែច្រើន
            ដើម្បី​បំពេញ​ចំណង់​ទាំង​ផ្លូវ​កាយ និង​ផ្លូវ​អារម្មណ៍​ ដែល​កំពុង​តែ​ញៀន ។<br>
            ឥទ្ធិ​ពល​របស់​នីកូ​ទីន -នី​កូ​ទីន​ភ្ញោច​ទៅ​លើ​ប្រព័ន្ធ​សរសៃ​ប្រសាទ ហើយ​អាច​​ធ្វើ​ឱ្យ​សារ​ពាង្គ​កាយ​ញ័រ
            (ចលនា​អចេតនា) ចំពោះ​អ្នក​ដែល​មិន​ធ្លាប់​ប្រើ ឬ​អាច​ធ្វើ​ឱ្យ​<br>
            ប្រកាច់​នៅ​ពេល​ដែល​ពួក​គេ​ជក់​ច្រើន ។ -នី​កូ​ទីន​បង្កើន​សម្ពាធ​ឈាម ចង្វាក់​បេះ​ដូង
            និង​​លំ​ហូរ​នៃ​ចរន្ត​ឈាម​ពី​បេះ​ដូង ។ នី​កូ​ទីន​ក៏​ធ្វើ​ឱ្យ​​សរសៃ​ឈាម​អាទែ​រួម​តូច​ដែរ ។<br>
            -នី​កូ​ទីន​ក៏​អាច​ធ្វើឱ្យ​បែក​ញើស និង​ចង្អោរ​ផង​ដែរ ។
            នី​កូ​ទីន​ធ្វើ​ឱ្យ​កំរិត​ជាតិ​ស្ករ​នៅ​ក្នុង​ឈាម​​កើនឡើង ។ -​នី​កូទីន​ធ្វើ​ឱ្យ​មាន​ការ​​ចង​ចាំ​ និង​ស្វា​ហាប់
            (មួយ​រយៈ) ។ នី​កូ​<br>
            ទីន​ក៏អាច​បន្ថយ​ការ​ឃ្លាន​អា​ហារ​ដែរ ។ -កំរិត​ជាតិ​នី​កូ​ទីន​អាច​នៅ​ក្នុង​ឈាម រយៈ​ពេល​៦​ទៅ​៨​ម៉ោង
            បន្ទាប់​ពី​ឈប់​ជក់បារី​ ។ រោគ​សញ្ញា​ញៀន​នី​កូទីន -ឆាប់​ខឹង -​ការ​ថប់​<br>
            អារម្មណ៍ -​ពិបាក​ផ្ចង់​អារម្មណ៍ -​នៅ​មិនស្ងៀម -​ចង្វាក់​បេះ​ដូង​ថយ​ចុះ -​ឃ្លា​ន​អាហារ
            ការ​ពិត​នៃ​រោគ​សញ្ញា​ញៀន -រោគ​សញ្ញា​ញៀន​តែង​កើត​ឡើង​ ក្នុង​រយៈ​ពេល​ប៉ុន្មាន​ម៉ោង<br>
            ក្រោយ​ពី​ការ​ជក់​បារី​ចុង​ក្រោយ​បំផុត ហើយ​វា​មាន​កំរិត​ខ្ពស់​បំផុត​ក្នុង​រយៈ​ពេល​ពីរទៅបីថ្ងៃ ។
            -​រោគស​ញ្ញា​​ញៀន​អាច​បាត់​ទៅ​វិញ​ក្នុង​រយៈ​ពេល​​ពី​របី​ថ្ងៃ​ទៅ​ពី​របី​សប្តាហ៍ ។<br>
            -រោគ​សញ្ញា​ញៀន អាច​ពិបាក​ទ្រាំ ប៉ុន្តែ​វា​ប្រសើ​រជាង​ការ​ពន្យារ​ពេល​ប្រឈម​ទៅនឹង​បញ្ហា​សុខ​ភាព និង​អនាគត ។
            ផល​​ប៉ះ​ពាល់​ដល់​សុខ​ភាព ការ​ជក់​បារីធ្វើ​ឱ្យ​ប៉ះ​ពាល់​ដល់​<br>
            សុខ​ភាពជា​ច្រើន​យ៉ាង​ ដូចជា បណ្តាល​ឱ្យ​មានជំងឺ​មហារីក និង​​ជំងឺ​ធ្ងន់​ធ្ងរ​ផ្សេងៗ​ទៀត ៖
            ១-ជំងឺ​បេះ​ដូង-សរសៃ​ឈាម​-ជំងឺ​បេះ​ដូង-​សរសៃ​ឈាម គឺជាមូល​ហេតុ​សំខាន់​មួយ​<br>
            នៃ​ការ​ស្លាប់​ដោយ​សារ​ការ​ជក់​បារី -ការ​ជក់បារី​ជំរុញ​ឱ្យ​សរសៃ​ឈាម​អា​ទែទៅ​ជា​រឹង និង​ត្បៀត
            ដែលជា​ហេតុ​បណ្តាល​ឱ្យ​កើត​ជំងឺ​លើស​ឈាម ស្ត្រូក និង​ជំងឺ​គាំង​បេះ​ដូង ។អ្នក​ជក់​បារី​កើត​ជំងឺ​ទាំង​នេះ
            ឆាប់​រហ័ស​ជាង​អ្នក​មិនជក់​បារី ។<br>
            -ប្រហែល​៣០%នៃ​ជំងឺ​គាំង​បេះ​ដូង បង្ក​ឡើង​​ដោយ​ការ​ជក់​បារី ។ ២-​ជំងឺ​មហារីក
            -អ្នកជក់​បារី​ងាយ​កើត​ជំងឺ​មហារីកជាង​អ្នក​មិន​ជក់​បារី ជា​ពិសេស ជំងឺ​មហារី​កសួត មហារី​ក​បំពង់​ក
            និង​មហារី​កមាត់ ដែលជំងឺ​ទាំង​នេះ​កម្រ​នឹងកើត​​<br>
            មាន​លើ​អ្នក​មិនជក់បារី ។ -បើអ្នក​ជក់បារី ជក់​កាន់តែ​ច្រើន​ក្នុង​មួយថ្ងៃ និង​ជក់​រយៈ​ពេល​កាន់តែ​យូរ
            នោះ​ពួក​គេ​កាន់​តែ​ប្រឈម​នឹង​ការ​កើត​ជំងឺ​មហារី​កសួត ។ ដូ​ចគ្នា​នោះ​ដែរ
            ការ​ប្រឈម​នឹង​ការ​កើត​ជំងឺ​នេះ​ក៏​កើន​ឡើង​ដែរ បើ​ពួកគេ​<br>
            ចាប់​ផ្តើម​ជក់បារី​ក្នុង​វ័យ​កាន់តែ​ក្មេង ។ -ចំពោះ​អតីត​អ្នក​ជក់​បារី ការ​ប្រឈម​នឹង​ការ​កើត​ជំងឺ​មហារីក​​សួត
            នឹ​ងធ្លាក់​ចុះ​មកស្មើ​នឹង​អ្នក​មិន​ជក់​បារី​ក្នុង​រយៈ​ពេល​​ប្រហែល​១៥​ឆ្នាំ ។
            -អ្នកជក់​បារី​មាន​ការ​ប្រឈម​នឹង​ការ​កើត​ជំងឺ​មហារីក​មាត់ បួន<br>
            ​ដង ខ្ពស់​ជាង​អ្នក​មិន​ជក់​បារី​។ -​ជំងឺ​ផ្សេងៗ​ទៀត ដែលកើត​មាន​ជា​ញឹក​ញាប់​​លើ​អ្នក​ជក់​បារី​មាន ៖
            -មហារីក​​ប្លោក​នោម -​មហារីក​បំពង់អាហារ -​មហារី​ក​តម្រង​នោម -មហារីកលំពែង ៣-​ជំងឺ​ស្ទះ​ផ្លូវ​ដង្ហើម​រ៉ាំ​រ៉ៃ
            (COPD) -ជំងឺ​ស្ទះ​ផ្លូវដង្ហើម​រ៉ាំ​រ៉ៃ គឺជា​<br>
            ក្រុម​ជំងឺ ដែល​ធ្វើ​ឱ្យ​ស្ទះ​ខ្យល់​ដក​ដង្ហើម និង​ធ្វើ​ឱ្យ​ពិបាក​ដក​ដង្ហើម ដូចជា ជំងឺ​ហើម​សួត (Emphysema)
            និងជំងឺ​រលាក​ទង​សួត​រ៉ាំ​រ៉ៃ ។ -ការ​ជក់បារី​គឺជាមូល​ហេតុ​ចំបង​មួយ​នៃ​ជំងឺ​ស្ទះ​​ផ្លូវ​ដង្ហើម​រ៉ាំ​រ៉ៃ ។
            -ចំពោះ​អ្នក​ជក់​បារី ដំណើរ​ការ​របស់​សួត អាច<br>
            ​ធ្លាក់​ចុះ​ទាប​ជាង​ធម្ម​តា​បី​ដង ។
            នៅ​ពេល​ដែល​​ដំណើរ​ការ​របស់​សួត​ធ្លាក​់ចុះការ​ពិបាក​ដក​ដង្ហើម​ក៏​ចាប់​ផ្តើម​កើត​ឡើង ។ -ការ​ខូចសួត
            ដោយសារ​ជំងឺ​ស្ទះ​ផ្លូវ​ដង្ហើម​រ៉ាំ​រ៉ៃ គឺជា​ការ​ខូច​ខាត​ជា​អចិន្ត្រៃ​យ៍
            ប៉ុន្តែ​ការ​ឈប់​ជក់​បារី​ក្នុង​ដំណាក់​កាល​ណាមួយ <br>
            អាច​កាត់​បន្ថយ​ការ​ធ្លាក់​ចុះ​នៃ​សមត្ថ​ភាព​របស់​សួត ។​៤-ការ​ជក់​បារី និង​ការ​ចុះ​ខ្សោយ​ផ្លូវ​ភេទ
            ចំពោះ​បុរស​ក្នុង​វ័យ​៣០ ទៅ​៤០​ឆ្នាំ ការ​ជក់​បារី​បង្កើន​ការ​ប្រឈម​នឹង​ការ​ចុះ​ខ្សោយ​ផ្លូវ​ភេទ ប្រហែល​៥០% ។
            លិង្គ​របស់​បុរស​នឹង​មិន​អាច​រឹង​បានទេ បើ<br>
            ​ចរន្ត​ឈាម​មិន​អាច​ហូរ​ចូលទៅ​លិង្គ​បាន​ដោយ​ស្រួល​​នោះ
            ដូច្នេះ​សរសៃ​ឈាម​ទាំង​នេះត្រូវតែ​មាន​ទ្រង់ទ្រាយ​ល្អជា​និច្ច ។ ការជក់​បារីអាច​បណ្តាល​ឱ្យ​ខូច​សរសៃ​ឈាម ៖
            នី​កូទីន​ធ្វើ​ឱ្យ​ត្បៀត​សរសៃ​ឈាម​អាទែ ដែល​ចូលទៅ​លិង្គ ជា​ហេតុ​ធ្វើ​ឱ្យ​លំហូរឈាម និង<br>
            ​សំពាធ​​ឈាមទៅ​លិង្គ​មានការ​ថយ​ចុះ ។ ឥទ្ធិពល​នៃ​ការ​ត្បៀត​សរសៃឈាម​នេះ​ចេះ​តែ​កើន​ឡើង
            ដូច្នេះ​ប្រសិន​បើ​អ្នក​ជក់បារី​គ្មាន​បញ្ហា​នេះ​កើត​ឡើង​ក្នុង​ពេល​បច្ចុ​ប្បន្ន​ក៏​ដោយ
            ក៏​​ពួក​គេ​​នឹង​អាច​មាន​បញ្ហា​នេះ​នៅពេលអនាគត ។ ការ​មាន​បញ្ហា​ផ្លូវ​<br>
            ភេទ​លើ​អ្នកជក់បារី អាច​ជា​រោគ​សញ្ញា​ដំបូង​ដែល​បង្ហាញ​ថា
            បារី​បាន​កំពុង​​បំផ្លាញ​ផ្នែក​ផ្សេងៗ​នៃ​សរី​រាង្គ​រួចទៅហើយ ដូចជា​សរសៃ​ឈាម​ទៅ​បេះ​ដូង​ជា​ដើម
            ។​៥-ការជក់​បារី​ក្នុង​ពេលមាន​ផ្ទៃ​ពោះ ការជក់​​បារី​ធ្វើ​ឱ្យប៉ះ​ពាល់​ផ្នែកជាច្រើន និង​គ្រប់​<br>
            ដំណាក់​កាលនៃ​ការ​បន្ត​ពូជ ។ ការ​ស្រាវ​ជ្រាវ​បាន​​បង្ហាញ​ឱ្យ​ឃើញ​ថា
            ការ​ជក់បារី​ក្នុង​ពេល​មាន​ផ្ទៃ​ពោះ​ប៉ះ​ពាល់​ដល់ទាំង​សុខ​ភាព​ម្តាយ ​និង​ទារក ។
            ជាតិ​នី​កូទីន​នៅ​ក្នុង​ថ្នាំ​​ជក់ ធ្វើ​ឱ្យ​ត្បៀត​សរសៃ​ឈាម​ក្នុង​ទ​ងសុក និង​ស្បូន ដែលជា​ហេតុ​ធ្វើ​ឱ្យ​<br>
            ​បរិមាណ​អុក​ស៊ី​ហ្សែន ដែល​ផ្តល់​ទៅទារក មាន​ការ​ថយ​ចុះ ។ នៅពេល​មាន​ផ្ទៃ​​ពោះ ស្ត្រី​ដែល​ជក់​បារី
            មាន​ការ​ប្រឈម​នឹង​ការ​មាន​បញ្ហាទ្វេរ​ដង ដូចជា ការ​បេះ​សុក (សុក​របេះ​ពី​ជញ្ជាំង​ស្បូន​មុន​អាយុ​កាល) ។
            បញ្ហា​នេះ​អាចធ្វើ​ឱ្យ​​ទារក​កើត​<br>
            មិន​គ្រប់​ខែ ស្លាប់​កើត​ ឬ​កើត​ស្លាប់ ។ នី​កូ​ទីន
            ក៏​ត្រូវ​បាន​រកឃើញ​មាននៅ​ក្នុង​ទឹក​ដោះ​ម្តាយ​ដែលជក់​បារី​ដែរ ។ ទារក​កើត​ពី​ម្តាយ
            ដែល​ជក់បារី​ក្នុ​ងពេល​មាន​ផ្ទៃពោះ តែង​មាន​ទំនង់​ទាប​ជាង​ធម្ម​តា ។ ការ​មានទំងន់​ទាបនេះ គឺ​ជា​<br>
            មូ​ល​ហេតុ​នៃ​ការ​ស្លាប់​របស់ទារក ។</font>
    </p>
</body>

</html>
